name: song4story
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas
  - scipy
  - scikit-learn
  - faiss-cpu=1.7.4
  - pytorch=2.4.1
  - torchvision=0.19.1
  - cpuonly
  - pip
  - pip:
      # make sure pip doesn’t fetch GPU builds
      - --index-url https://download.pytorch.org/whl/cpu
      - --extra-index-url https://pypi.org/simple
      # keep torch/vision pinned to the same versions as conda
      - torch==2.4.1
      - torchvision==0.19.1
      # your other deps
      - streamlit==1.50.0
      - transformers==4.40.2
      - accelerate==1.10.1
      - sentencepiece==0.2.1
      - open_clip_torch==3.2.0
      - clip-interrogator==0.6.0
      - ftfy==6.3.1
      - wordfreq==3.1.1
      - pyarrow==21.0.0


